stages:
  preprocess:
    cmd: python src/pipeline/01_prep.py
    deps:
    - src/pipeline/01_prep.py
    - src/prep_funcs.py
    - ${preprocess.source_fights_fn}
    - ${preprocess.source_coef_fn}
    - ${preprocess.source_fighters_fn}
    outs:
    - ${preprocess.prep_fights_fn}
    - ${preprocess.prep_fighters_fn}
    - ${preprocess.prep_coef_fn}
  filter:
    cmd: python src/pipeline/02_filter.py
    deps:
    - ${preprocess.prep_fights_fn}
    - ${preprocess.prep_fighters_fn}
    - ${preprocess.prep_coef_fn}
    - src/pipeline/02_filter.py
    outs:
    - ${filter.filt_fights_fn}
  stat_feat_gen:
    cmd: python src/pipeline/03_stat_feat_gen.py
    deps:
    - ${filter.filt_fights_fn}
    - src/pipeline/03_stat_feat_gen.py
    - src/stat_funcs.py
    params:
    - stat_feat_gen.min_fights_num
    - stat_feat_gen.rol_window_size
    - stat_feat_gen.aggs
    - stat_feat_gen.cust_aggs
    outs:
    - ${stat_feat_gen.feat_fn}
  fights_feat_gen:
    cmd: python src/pipeline/04_fights_feat_gen.py
    deps:
    - ${stat_feat_gen.feat_fn}
    - src/pipeline/04_fights_feat_gen.py
    outs:
    - ${fights_feat_gen.feat_fn}
  split_data:
    cmd: python src/pipeline/05_split_data.py
    deps:
    - src/pipeline/05_split_data.py
    - ${fights_feat_gen.feat_fn}
    params:  
    - split_data.train_prop
    - split_data.ohe_fn
    outs:
    - ${split_data.feat_full_fn}
  feat_filter_rules:
    cmd: python src/pipeline/06_feat_filter_rules.py
    deps:
    - src/pipeline/06_feat_filter_rules.py
    - ${split_data.feat_full_fn}
    params:  
    - feat_filter_rules.drop_highpsi_thresh
    outs:
    - ${feat_filter_rules.feat_fn}
  feat_longlist_sel:
    cmd: python src/pipeline/07_feat_longlist_sel.py
    params:
    - feat_longlist_sel.method
    - feat_longlist_sel.thresh
    - feat_longlist_sel.topn_feats
    deps:
    - ${feat_filter_rules.feat_fn}
    - ${split_data.feat_full_fn}
    - src/pipeline/07_feat_longlist_sel.py
    outs:
    - ${feat_longlist_sel.feat_long_fn}
    - ${feat_longlist_sel.sign_feat_long_all_fn}
    - ${feat_longlist_sel.sign_feat_long_fn}
  feat_shortlist_sel:
    cmd: python src/pipeline/08_feat_shortlist_sel.py
    params:
    - feat_shortlist_sel.quantile_clip
    deps:
    - ${feat_longlist_sel.feat_long_fn}
    - src/pipeline/08_feat_shortlist_sel.py
    outs:
    - ${feat_shortlist_sel.sign_feat_short_all_fn}
    - ${feat_shortlist_sel.sign_feat_short_fn}
    - ${feat_shortlist_sel.feat_anom_fn}
    - ${feat_shortlist_sel.feat_short_fn}
  train_eval:
    cmd: python src/pipeline/09_train_eval.py
    params:
    - train_eval.model
    - seed
    deps:
    - ${feat_shortlist_sel.feat_short_fn}
    - src/pipeline/09_train_eval.py
    outs:
    - ${train_eval.model_fn}
    - ${train_eval.score_df_fn}
    metrics:
    - ${train_eval.eval_fn}
  calc_report:
    cmd: python src/pipeline/10_calc_report.py
    params:
    - calc_report.alpha
    deps:
    - ${train_eval.model_fn}
    - ${train_eval.score_df_fn}
    - src/pipeline/10_calc_report.py
    - src/inference.py
    metrics:
    - ${calc_report.report_metrics_fn}
    
