stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    - ${preprocess.source_fn}
    - ${preprocess.source_coef_fn}
    outs:
    - ${preprocess.prep_fn}
    - ${preprocess.prep_coef_fn}
  filter:
    cmd: python src/filter.py
    deps:
    - ${preprocess.prep_fn}
    - ${preprocess.prep_coef_fn}
    - src/filter.py
    outs:
    - ${filter.filt_fn}
  stat_feat_gen:
    cmd: python src/stat_feat_gen.py
    deps:
    - ${filter.filt_fn}
    - src/stat_feat_gen.py
    - src/funcs.py
    params:
    - stat_feat_gen.min_fights_num
    - stat_feat_gen.rol_window_size
    - stat_feat_gen.aggs
    - stat_feat_gen.cust_aggs
    outs:
    - ${stat_feat_gen.feat_fn}
  fights_feat_gen:
    cmd: python src/fights_feat_gen.py
    deps:
    - ${stat_feat_gen.feat_fn}
    - src/fights_feat_gen.py
    outs:
    - ${fights_feat_gen.feat_fn}
  split_data:
    cmd: python src/split_data.py
    deps:
    - src/split_data.py
    - ${fights_feat_gen.feat_fn}
    params:
    - split_data.quantile_clip  
    - split_data.train_prop
    outs:
    - ${split_data.feat_full_fn}
    - ${split_data.feat_anom_fn}
  feat_longlist_sel:
    cmd: python src/feat_longlist_sel.py
    params:
    - feat_longlist_sel.method
    - feat_longlist_sel.thresh
    - feat_longlist_sel.topn_feats
    deps:
    - ${split_data.feat_full_fn}
    - src/feat_longlist_sel.py
    outs:
    - ${feat_longlist_sel.feat_long_fn}
    - ${feat_longlist_sel.sign_feat_long_fn}
  feat_shortlist_sel:
    cmd: python src/feat_shortlist_sel.py
    deps:
    - ${feat_longlist_sel.feat_long_fn}
    - src/feat_shortlist_sel.py
    outs:
    - ${feat_shortlist_sel.feat_short_fn}
  train_eval:
    cmd: python src/train_eval.py
    deps:
    - ${feat_shortlist_sel.feat_short_fn}
    - src/train_eval.py
    params:
    - seed
  
